### ISSUE TITLE
Documentation - Corrections

### ISSUE THREAD

**Issue by JohnCoene** [weijianzhang/Word2Vec.jl#13]
Unless I am mistaken, in `word2phrase`

```julia
"""
threshold <AbstractFloat>
      	      The <AbstractFloat> value represents threshold for 
              forming the phrases (higher means less phrases); default 100
"""
```

It's not a float but an int.

In `word2cluster(train, output, classes; ...)` It's actually plural `word2clusters`.

Awesome package, thanks!

**Comment by aviks** [comment]
Sorry, nobody responded to this in time, but should be fine now.

**Comment by aviks** [comment]
threshold is actually defined as a float in the c code

https://github.com/JuliaText/Word2Vec.jl/blob/master/deps/src/word2vec-c/word2phrase.c#L328

spelling of `word2clusters` is now fixed.
